version: 2
jobs:
  build:
    docker:
      - image: microsoft/aspnetcore-build:2.0

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Restore 
          command: dotnet restore notes/
      - run:
          name: Build 
          command: dotnet build notes/

      - run:
          name: Run tests 
          command: dotnet test notes_test/notes_test.csproj

      - run:
          name: Publish 
          #command: dotnet publish c Release -r ubuntu.16.04-x64 notes/notes.csproj  --output ../publish
          command: dotnet publish -c Release -r ubuntu.16.04-x64 notes/notes.csproj  --output ../publish


      - add_ssh_keys:
          fingerprints:
            - "60:a4:59:d0:38:2b:c3:00:bf:a3:b8:63:9d:ab:7c:a0"

      - deploy:
          name: Deploy Over SSH
          command: scp  -o StrictHostKeyChecking=no -r ~/repo/publish  ubuntu@ec2-18-206-57-23.compute-1.amazonaws.com:/var/www/html/notes/


  